# ----------------------------------------------------------------
# Builder
# ----------------------------------------------------------------
FROM golang:1.12 as builder

# take advantage of build cache by downloading modules before copying sources
WORKDIR /app
COPY go.mod .
RUN go mod download

# build the service binary
COPY . .
RUN CGO_ENABLED=0 go build -o service ./cmd

# ----------------------------------------------------------------
# Service Image
# ----------------------------------------------------------------
FROM scratch as service
COPY cmd/res /res
COPY --from=builder /app/service /service
EXPOSE 49993 9001
ENTRYPOINT ["./service"]
CMD ["--registry=consul://edgex-core-consul:8500","--profile=docker","--confdir=/res"]
