[Service]
Host = "tempo-device-service"
Port = 49993
ConnectRetries = 3
Labels = []
OpenMsg = "tempo-device-service started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "/logs/tempo-device-service.log"

[Writable]
LogLevel = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Driver]
  # POST output of hcidump to <host>:<ListenAddress>/hcidump;
  # see sendhci.sh for an example.
  ListenAddress = "9001"
  # decoding mode can be "strict" or "non-standard"
  # "strict" expect an exact length & value match against an expected packet
  # "non-standard" uses a regular expression to guess portions of the message,
  # which may be necessary if a given HCI device sends data in a non-standard
  # way.
  DecodingMode = "non-standard"
