name: tempo-device-service
base: core18
version: git
license: Apache-2.0
version-script: |
  echo $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: Decode Tempo Disc BLE advertisements for EdgeX
title: Tempo Disc EdgeX Device Service
description: |
  Accepts hcidump data via HTTP, attempts to decode it as Tempo Disc data, and
  if successful, sends current temperature readings to EdgeX.

architectures:
  - build-on: amd64
  - build-on: arm64

grade: devel
confinement: strict

# edinburgh release is epoch 1
epoch: 1

# TODO: consider adding BLE scanning directly (though perhaps confine that elsewhere)
apps:
  tempo-device-service:
    adapter: none
    command: bin/tempo-device-service -confdir $SNAP_DATA/config/tempo-device-service profile res --registry $CONSUL_ADDR
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
    daemon: simple
    plugs: [network, network-bind]

parts:
  go:
    plugin: go
    source: .
    build-packages: [curl]
    override-build: |
      # use dpkg architecture to figure out our target arch
      # note - we specifically don't use arch
      case "$(dpkg --print-architecture)" in
        amd64)
          FILE_NAME=go1.11.9.linux-amd64.tar.gz
          FILE_HASH=e88aa3e39104e3ba6a95a4e05629348b4a1ec82791fb3c941a493ca349730608
          ;;
        arm64)
          FILE_NAME=go1.11.9.linux-arm64.tar.gz
          FILE_HASH=892ab6c2510c4caa5905b3b1b6a1d4c6f04e384841fec50881ca2be7e8accf05
          ;;
        armhf)
          FILE_NAME=go1.11.9.linux-armv6l.tar.gz
          FILE_HASH=f0d7b039cae61efdc346669f3459460e3dc03b6c6de528ca107fc53970cba0d1
          ;;
        i386)
          FILE_NAME=go1.11.9.linux-386.tar.gz
          FILE_HASH=0fa4001fcf1ef0644e261bf6dde02fc9f10ae4df6d74fda61fc4d3c3cbef1d79
          ;;
      esac
      # download the archive, failing on ssl cert problems
      curl https://dl.google.com/go/$FILE_NAME -O
      echo "$FILE_HASH $FILE_NAME" > sha256
      sha256sum -c sha256 | grep OK
      tar -C $SNAPCRAFT_STAGE -xf go*.tar.gz --strip-components=1
    prime:
      - "-*"

  tempo-device-service:
    source: .
    plugin: make
    after: [go]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build

      install -DT "./cmd/tempo-device-service" "$SNAPCRAFT_PART_INSTALL/bin/tempo-device-service"
      install -DT "./LICENSE" "$SNAPCRAFT_PART_INSTALL/usr/share/doc/tempo-device-service/LICENSE"
      install -d "$SNAPCRAFT_PART_INSTALL/config/tempo-device-service/res/"

      # Override 'LogFile' and 'LoggingRemoteURL'
      cat "./cmd/res/configuration.toml" | \
        sed -e s:\"./tempo-device-service.log\":\'\$SNAP_COMMON/tempo-device-service.log\': \
          -e s:'ProfilesDir = \"./res\"':'ProfilesDir = \"\$SNAP_DATA/config/tempo-device-service/res\"': > \
        "$SNAPCRAFT_PART_INSTALL/config/tempo-device-service/res/configuration.toml"

